### ISSUE TITLE
docker化的尝试

### ISSUE THREAD

**Issue by nickhoo555** [ttqftech/FFBox#47]
Hi，滔滔，

我在尝试将此项目打成 docker 在nas上使用，目前跑起来了

[https://github.com/nickhoo555/FFBox](https://github.com/nickhoo555/FFBox)

但是发现了一个比较尴尬的处境：
我要处理的输入文件在nas上，但是前端目前好像只能上传本地文件作为输入，

特来咨询，有无计划兼容 直接输入文件路径 作为输入，
或者类似 handbrak，设置一个 watch 目录来自动作为输入。

**Comment by ttqftech** [comment]
实测了一下，ffmpeg 支持很多种类的网络协议作为输入，包括 RTSP、Windows SMB、ftp 之类。[FFmpeg Protocols Documentation](https://www.ffmpeg.org/ffmpeg-protocols.html)
用路径字符串作为输入这个设计可以有。

至于 watch 目录，可以考虑作为个未来的大功能吧，以后有机会加上。

**Comment by ttqftech** [comment]
@nickhoo555 4.2 版本加入了直接按 url 作为输入的功能，可以体验一下。
如果还有什么想法的话欢迎提出☺️

**Comment by nickhoo555** [comment]
🐮🍺！
